### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by Jyoti-Kabir** [dhruv-2015/JIOTVServer#15]
**node index.js** or **./start.sh** throws this error :-
```
SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
file:///home/bakshi/JTVServer/build/handler.js:1217
					req.connection?.remoteAddress ||
					               ^
```

OS: **Xubuntu 22.04 LTS**
Nodejs version: **v12.22.9**
npm version: **8.5.1**

**Comment by Jyoti-Kabir** [comment]
When I clone this repo, install the packages and run start.sh, I get the following error :-

```
SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
file:///home/bakshi/Downloads/JIOTVServer/build/handler.js:1101
await server.init({ env: process.env });
^^^^^
```

**Comment by Jyoti-Kabir** [comment]
I am sorry, the problem was with the node version, it was pretty old.
